"""mistake fi

Revision ID: 9dbfcd04c1ee
Revises: 88c038a5993a
Create Date: 2026-04-05 15:48:31.847416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '9dbfcd04c1ee'
down_revision: Union[str, Sequence[str], None] = '88c038a5993a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_vrified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_vrified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
